### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by thefoxcc** [FedericoHeichou/PizzaReader#56]
How do I implement my localization?
https://github.com/thefoxcc/teammanga/blob/master/lang/ru.json
https://github.com/thefoxcc/teammanga/blob/master/resources/js/lang/ru.js

**Comment by FedericoHeichou** [comment]
Hi,
As you can see from the readme you just need to edit APP_LOCALE in your
.env file to change the language.
Open the .env file and type "ru" near "APP_LOCALE="

After that you have to run "php artisan config:cache" (you must run this
everytime you edit your .env file else new settings could not be loaded
immediately)

Il mar 28 nov 2023, 18:21 thefoxcc ***@***.***> ha scritto:

**Comment by thefoxcc** [comment]
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/26c089ae-c941-4ada-856f-962beec689d0)
error chapter

**Comment by FedericoHeichou** [comment]
> ![image](https://private-user-images.githubusercontent.com/94108436/286357261-26c089ae-c941-4ada-856f-962beec689d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTU1NzAsIm5iZiI6MTcwMTE5NTI3MCwicGF0aCI6Ii85NDEwODQzNi8yODYzNTcyNjEtMjZjMDg5YWUtYzk0MS00YWRhLTg1NmYtOTYyYmVlYzY4OWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE4MTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmUzNDhlMmRlYmEwYzNiNGI5NjkwZDU2ODAxNzQzZDViYTc2NjQxOGYwMzUwY2FkNzJiYWRiZmQ0OGM4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3AEoBR_MDb8IOaCAu_L0eOoyGdpzD5zEcmcmvmDQuY) error chapter

Try to rename the file in something like 001.jpg to check if everything works. Personally I never tried to use cyrillic characters in file names

**Comment by thefoxcc** [comment]
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/84b65ce3-1c60-4bf4-9979-260f712f0ebd)
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/d8961fee-819f-4b15-90f6-5a293f9ab928)
strangely enough from 2 mb above does not seem to download, although the process at 100 goes but an error ((

**Comment by thefoxcc** [comment]
another moment pdf downloads empty but zip works.
------------------
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/0267e242-be57-497f-87bf-6952710d4db2)
how can I change this particular text? to have a manga instead of a comic

**Comment by FedericoHeichou** [comment]
> ![image](https://private-user-images.githubusercontent.com/94108436/286367849-84b65ce3-1c60-4bf4-9979-260f712f0ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTk3ODgsIm5iZiI6MTcwMTE5OTQ4OCwicGF0aCI6Ii85NDEwODQzNi8yODYzNjc4NDktODRiNjVjZTMtMWM2MC00YmY0LTk5NzktMjYwZjcxMmYwZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE5MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOThhM2M2OTFmZWY1MjUyMWY5NzRkM2FhYzUyNTgwZTc0OGI4MjU1NGMyMmFiN2ZhYjM4NTM1YmJiYTdkYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NcGm5wcdbVyY85Ub9NgB1Wmcj8MoLAJAvo3zyR-_SA) ![image](https://private-user-images.githubusercontent.com/94108436/286368763-d8961fee-819f-4b15-90f6-5a293f9ab928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTk3ODgsIm5iZiI6MTcwMTE5OTQ4OCwicGF0aCI6Ii85NDEwODQzNi8yODYzNjg3NjMtZDg5NjFmZWUtODE5Zi00YjE1LTkwZjYtNWEyOTNmOWFiOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE5MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTZiZjc1ZjFkMGI1MWI5YzRjMzg5ZTM1NjZjZWE0NWM4NDczZGFiMjA0MDQ0ZTgzMDlkYWIyNjM3YjkyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WhCazqGtP2SGoblNx2STVew2FT0es0d8UanR26JKLVs) strangely enough from 2 mb above does not seem to download, although the process at 100 goes but an error ((

Oh ok, I think it is a server misconfiguration.  
Seems you configured max upload size and max post size in your php.ini (the default value is pretty small) at 2MB.

Try to add in the end of your /etc/php/php.ini something like that

```
upload_max_filesize = 500M
post_max_size = 500M
```

Then restart your apache
```
systemctl restart apache2
```
Or your fpm if you are using that
```
systemctl restart php-fpm
```

**Comment by FedericoHeichou** [comment]
> ## another moment pdf downloads empty but zip works.
> ![image](https://private-user-images.githubusercontent.com/94108436/286377629-0267e242-be57-497f-87bf-6952710d4db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMDA0MDUsIm5iZiI6MTcwMTIwMDEwNSwicGF0aCI6Ii85NDEwODQzNi8yODYzNzc2MjktMDI2N2UyNDItYmU1Ny00OTdmLTg3YmYtNjk1MjcxMGQ0ZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE5MzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTgxOGFhYmM1ODc0YzliZmFkNTA3ZGY1MzZlMDQxMGRlYmExMTliN2FmMTExYTZhZWFiOWNjY2VkODQ1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pDiJFqLIotRPTM14vX66tJc9jNUNUEu6Ch4_J7Zr43Q) how can I change this particular text? to have a manga instead of a comic

You should use a custom localization like you did in the first post (with ru.json and ru.js). If you want to keep english create en.json and en.js, should still work

**Comment by FedericoHeichou** [comment]
> ## another moment pdf downloads empty but zip works.

Pdf doesn't work if your local installation of imagemagick has PDF disabled.

Remove this line
```
<policy domain="coder" rights="none" pattern="PDF" />
```
From `/etc/ImageMagick-6/policy.xml`

**Comment by thefoxcc** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94108436/286367849-84b65ce3-1c60-4bf4-9979-260f712f0ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTk3ODgsIm5iZiI6MTcwMTE5OTQ4OCwicGF0aCI6Ii85NDEwODQzNi8yODYzNjc4NDktODRiNjVjZTMtMWM2MC00YmY0LTk5NzktMjYwZjcxMmYwZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE5MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOThhM2M2OTFmZWY1MjUyMWY5NzRkM2FhYzUyNTgwZTc0OGI4MjU1NGMyMmFiN2ZhYjM4NTM1YmJiYTdkYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NcGm5wcdbVyY85Ub9NgB1Wmcj8MoLAJAvo3zyR-_SA) ![image](https://private-user-images.githubusercontent.com/94108436/286368763-d8961fee-819f-4b15-90f6-5a293f9ab928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTk3ODgsIm5iZiI6MTcwMTE5OTQ4OCwicGF0aCI6Ii85NDEwODQzNi8yODYzNjg3NjMtZDg5NjFmZWUtODE5Zi00YjE1LTkwZjYtNWEyOTNmOWFiOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE5MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTZiZjc1ZjFkMGI1MWI5YzRjMzg5ZTM1NjZjZWE0NWM4NDczZGFiMjA0MDQ0ZTgzMDlkYWIyNjM3YjkyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WhCazqGtP2SGoblNx2STVew2FT0es0d8UanR26JKLVs) strangely enough from 2 mb above does not seem to download, although the process at 100 goes but an error ((
> 
> Oh ok, I think it is a server misconfiguration. Seems you configured max upload size and max post size in your php.ini (the default value is pretty small, still should be enough to upload pictures) at 2MB.
> 
> Try to add in the end of your /etc/php/php.ini something like that
> 
> ```
> upload_max_filesize = 500M
> post_max_size = 500M
> ```
> 
> Then restart your apache
> 
> ```
> systemctl restart apache2
> ```
> 
> Or your fpm if you are using that
> 
> ```
> systemctl restart php-fpm
> ```

cd /etc/php/8.2/apache2/php.ini )) thanks

**Comment by thefoxcc** [comment]
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/1b20bf19-5da1-4945-8bcc-e4e002dcbee2)
how can I put my display setting and hide from the panel

**Comment by FedericoHeichou** [comment]
> Hint how to localize the /admin part too? [is it possible to manually replace words from /pizzareader/resources/views (is there another way?).]

Sadly I didn't add that feature yet.  
You have to manually edit them in `/pizzareader/resources/views`  but if I update the code there (it won't happen often but still it could) can be hard update your code because of merge conflicts.  

Tip: if you are searching for certain word you can use the command `grep` to find in which file it is.  
For example:
```bash
cd /var/www/pizzareader
grep -r 'Do you want to delete this chapter and its relative pages' --exclude-dir=vendor
```

**Comment by FedericoHeichou** [comment]
> ![image](https://private-user-images.githubusercontent.com/94108436/286592085-1b20bf19-5da1-4945-8bcc-e4e002dcbee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg0ODUsIm5iZiI6MTcwMTI3ODE4NSwicGF0aCI6Ii85NDEwODQzNi8yODY1OTIwODUtMWIyMGJmMTktNWRhMS00OTQ1LThiY2MtZTRlMDAyZGNiZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzYxOTY4MzJlMTMxM2IxZjM5MGE2ZTk3NTRhNDQ0NWM1ODQyNzIxODllMzFiYWY0MmQyMDkzMzA1ZDcxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbvAlAuy-AvYoVYEFy4nUZ_JjYOcBcK4bjE2dTV74Wc) how can I put my display setting and hide from the panel

If you mean that `Reader HTML` you must edit your `.env` file setting `EDIT_CUSTOM_HTML=true`.  
Remember to run as always `php artisan config:cache`.  
Now you can edit all the HTML fields in the settings page.  
Remember to set back `EDIT_CUSTOM_HTML=false` (and run `php artisan config:cache`), I don't suggest keep it enabled because if someone steals a admin account could inject custom javascript code and could be dangerous.  

Btw it is strange you have those values, the default value should be empty

**Comment by thefoxcc** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94108436/286592085-1b20bf19-5da1-4945-8bcc-e4e002dcbee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg0ODUsIm5iZiI6MTcwMTI3ODE4NSwicGF0aCI6Ii85NDEwODQzNi8yODY1OTIwODUtMWIyMGJmMTktNWRhMS00OTQ1LThiY2MtZTRlMDAyZGNiZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzYxOTY4MzJlMTMxM2IxZjM5MGE2ZTk3NTRhNDQ0NWM1ODQyNzIxODllMzFiYWY0MmQyMDkzMzA1ZDcxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbvAlAuy-AvYoVYEFy4nUZ_JjYOcBcK4bjE2dTV74Wc) how can I put my display setting and hide from the panel
> 
> If you mean that `Reader HTML` you must edit your `.env` file setting `EDIT_CUSTOM_HTML=true`. Remember to run as always `php artisan config:cache`. Now you can edit all the HTML fields in the settings page. Remember to set back `EDIT_CUSTOM_HTML=false` (and run `php artisan config:cache`), I don't suggest keep it enabled because if someone steals a admin account could inject custom javascript code and could be dangerous.
> 
> Btw it is strange you have those values, the default value should be empty

No, I mean the slider settings buttons.

**Comment by thefoxcc** [comment]
> > Hint how to localize the /admin part too? [is it possible to manually replace words from /pizzareader/resources/views (is there another way?).]
> 
> Sadly I didn't add that feature yet. You have to manually edit them in `/pizzareader/resources/views` but if I update the code there (it won't happen often but still it could) can be hard update your code because of merge conflicts.
> 
> Tip: if you are searching for certain word you can use the command `grep` to find in which file it is. For example:
> 
> ```shell
> cd /var/www/pizzareader
> grep -r 'Do you want to delete this chapter and its relative pages' --exclude-dir=vendor
> ```

Can't you create a base like .env?
