### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by thefoxcc** [FedericoHeichou/PizzaReader#57]
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/b02635f7-ab08-44b4-af86-b07369562b62)
Hi, this situation in the search works only in English, how can I add Cyrillic?
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/5b22504e-6a3a-4a5a-a2fd-771b78339d19)
in the files .vue changed the text Format: Manga and webtoon to Cyrillic, but after clearing the cache, nothing changed, as well as with adult 18+.
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/3c1b339c-8503-40f8-b9f8-c3e9fe8d4af7)
the volume download button does not work the reason why I may be getting 404

**Comment by FedericoHeichou** [comment]
Hi
> ![image](https://private-user-images.githubusercontent.com/94108436/287543556-b02635f7-ab08-44b4-af86-b07369562b62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzMyOTMsIm5iZiI6MTcwMTYzMjk5MywicGF0aCI6Ii85NDEwODQzNi8yODc1NDM1NTYtYjAyNjM1ZjctYWIwOC00NGI0LWFmODYtYjA3MzY5NTYyYjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE5NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyM2M0NzJlNDlkNGY1MWUzMWRlZjI4YWRmYjljMmZhYmY3NzhkNjY2YmQyMzVjNjY3ZGNmZWVmZWFmMGU4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Az8TDfGiYmEpyesd0dgv2ELSUfcYCljUSRmr6SeI9k) Hi, this situation in the search works only in English, how can I add Cyrillic?

This is the function used to search comics
https://github.com/FedericoHeichou/PizzaReader/blob/70609d78225cf5654fe40b4e86d4586ff0157f8e/app/Models/Comic.php#L89-L102

I did this in this way because it replace automatically symbols to permits research like `One Punch Man` returning things like `One-Punch man` or `Steins gate` can still return `Steins;Gate`.  
Sadly Cyrillic are all detected as symbols. I don't know if there is a way to say "all cyrillic alphabet" with regex, in Latin alphabet you can accomplish this with `A-Za-z`.  
Anyway if you don't want this feature you can replace that function with this code (not tested but should work):
```php
    public function scopeSearch($query, $search, $column='name') {
        $comic_name = $search;
        if(strlen($comic_name) > 2) {
            if ($column === 'name') {
                return $query->where(function ($q) use ($comic_name) {
                    $q->where('name', 'LIKE', '%' . $comic_name . '%')->orWhere('alt_titles', 'LIKE', '%' . $comic_name . '%');
                });
            } else {
                return $query->where($column, 'LIKE', '%' . $comic_name . '%');
            }
        } else { // Sorry mom
            return $query->where(DB::raw('1=2'));
        }
    }
```
Or you can edit it adding something near  both lines with 'A-Za-z` to make cyrillic works (the full list of characters is ok but I have totally not idea how many are they)

> ![image](https://private-user-images.githubusercontent.com/94108436/287543683-5b22504e-6a3a-4a5a-a2fd-771b78339d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzMyOTMsIm5iZiI6MTcwMTYzMjk5MywicGF0aCI6Ii85NDEwODQzNi8yODc1NDM2ODMtNWIyMjUwNGUtNmEzYS00YTVhLWEyZmQtNzcxYjc4MzM5ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE5NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZDdhNTAyZGQ3MDE2MTJhMmEyMTJkYTZhYzU1Y2M4ZmRjMDY3N2Q0NGI2OGMyNjkxNDY1YmVlYWU0NWRmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JRwZcDZDhjvjPEcsqF5XpbaT1kDghlIl0DRhHDWqDnc) in the files .vue changed the text Format: Manga and webtoon to Cyrillic, but after clearing the cache, nothing changed, as well as with adult 18+.  
You have to re-build the Vue files.  
First you have to install some dependencies if you have not them yet
```bash
apt install -y npm
```
Now enter the project directory and install node.js dependencies
```bash
cd /var/www/pizzareader
npm install
```
Now you can build everything again running
```bash
npm run prod
```
Now if you clear your cache you should see your edits

> ![image](https://private-user-images.githubusercontent.com/94108436/287543779-3c1b339c-8503-40f8-b9f8-c3e9fe8d4af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzMyOTMsIm5iZiI6MTcwMTYzMjk5MywicGF0aCI6Ii85NDEwODQzNi8yODc1NDM3NzktM2MxYjMzOWMtODUwMy00MGY4LWI5ZjgtYzNlOWZlOGQ0YWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE5NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODU1Y2FiZjljZjA2ODZjOGYxNzY2ZjI4YWE5M2UyYzlhMGUxMGNhZTY1Y2NmMzRjOTJkZWU1OGM0NWY5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rs1NFdgsfXRqLSytsdDByOrvoMQPLMdZD684NomCwB8) the volume download button does not work the reason why I may be getting 404

The name of volume is a bit strange, does you have problema with normal volumes too? This seems a oneshot.  
Can you try if you have the same problem with a volume 01, 02, 03 etc of a different serie? Else could still be a problem with cyrillic... Sadly I only tested it with UTF-8 characters, I'm sorry for those problems

**Comment by thefoxcc** [comment]
npm run prod


> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] Error: You are using an unsupported version of Node. Please update to at least Node v12.14
    at assertSupportedNodeVersion (/var/www/wamanga.ru/node_modules/laravel-mix/src/Engine.js:6:15)
    at module.exports (/var/www/wamanga.ru/node_modules/laravel-mix/setup/webpack.config.js:7:5)
    at loadConfigByPath (/var/www/wamanga.ru/node_modules/webpack-cli/lib/webpack-cli.js:1439:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pizzareader@1.0.2 production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pizzareader@1.0.2 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-12-04T20_15_33_654Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pizzareader@1.0.2 prod: `npm run production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pizzareader@1.0.2 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-12-04T20_15_33_677Z-debug.log

**Comment by thefoxcc** [comment]
![image](https://github.com/FedericoHeichou/PizzaReader/assets/94108436/59524951-6136-4bac-bee2-8126c7a5f501)
weirdly now I can't turn it on or off

**Comment by thefoxcc** [comment]
@FedericoHeichou
